### ISSUE TITLE
bug in `IrreducibleAffordingRepresentation`

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-packages/repsn#4]
The following problem has been found by Saad Bedaiwi.

Call GAP 4.12.1 or 4.12.2 or GAP from the current master branch and then enter:

```
gap> s:= PSL( 2, 11 );;
gap> sub:= AllSubgroups( s );;
gap> u:= First( sub, x -> Size(x) = 60);;
gap> chi:= Irr(u)[3];; chi[1];
3
gap> HasTrivialSubgroup(u);
true
gap> t:= TrivialSubgroup(u);;
gap> HasNaturalHomomorphismByNormalSubgroupNCInParent( t );
true
gap> NaturalHomomorphismByNormalSubgroupNCInParent( t );
[ (1,8,10)(2,7,9)(3,12,6)(4,11,5), (1,8)(2,7)(3,4)(5,9)(6,10)(11,12) ] -> 
[ (1,4,5)(2,6,3), (1,4)(3,5) ]
```

(Note that this natural homomorphism is an isomorphism. However, it is not an identity mapping but reduces the number of moved points. This does not happen if one creates `u` in an easier way.)

Now try to compute a representation for `chi`, using the Repsn package.

```
gap> LoadPackage("repsn");;
─────────────────────────────────────────────────────────────────────────────
Loading  Repsn 3.1.0 (Constructing representations of finite groups)
by Vahid Dabbaghian (http://www.sfu.ca/~vdabbagh).
maintained by:
   The GAP Team (support@gap-system.org).
Homepage: https://gap-packages.github.io/repsn/
Report issues at https://github.com/gap-packages/repsn/issues
─────────────────────────────────────────────────────────────────────────────
gap> rep := IrreducibleAffordingRepresentation( chi );;
Error, List Element: <list>[2] must have an assigned value in
[...]
```

The reason is that the code of `IrreducibleAffordingRepresentation` assumes that `NaturalHomomorphismByNormalSubgroupNC( G, Kernel( chi ) )` returns an identity mapping if `Kernel( chi )` is trivial.

I will provide a pull request that fixes this bug.

**Comment by hongyi-zhao** [comment]
The initial discussion on this issue is [here](https://lists.uni-kl.de/gap/arc/forum/2023-03/msg00086.html).
